- backend/.gitignore
- backend/docs/index.adoc
- backend/docs/index.html
- backend/src/main/java/com/backjoongwon/cvi/common/handler/CVIControllerAdvice.java
- backend/src/main/java/com/backjoongwon/cvi/user/application/UserService.java
- backend/src/main/java/com/backjoongwon/cvi/user/dto/LoginResponse.java
- backend/src/main/java/com/backjoongwon/cvi/user/ui/UserController.java
- backend/src/test/java/com/backjoongwon/cvi/user/ui/UserControllerTest.java
> feat: User 로그인 관련 docs 작성 (#11)

- backend/.gitignore
- backend/deploy/deploy.sh
- backend/deploy/health.sh
- backend/deploy/profile.sh
- backend/deploy/start.sh
- backend/deploy/stop.sh
- backend/deploy/switch.sh
- backend/src/main/java/com/backjoongwon/cvi/DataLoader.java
- backend/src/main/java/com/backjoongwon/cvi/deploy/ProfileController.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/backjoongwon/cvi/deploy/ProfileControllerTest.java
> [BE] 무중단 배포 및 문서화 #33

- frontend/src/components/SideBar/SideBar.js
> [FE] 처음 화면 렌더 시 api 호출하는 버그 수정 (#50)

- backend/src/main/java/com/backjoongwon/cvi/common/handler/CVIControllerAdvice.java
- backend/src/main/resources/console-appender.xml
- backend/src/main/resources/file-error-appender.xml
- backend/src/main/resources/file-info-appender.xml
- backend/src/main/resources/file-warn-appender.xml
- backend/src/main/resources/logback-spring.xml
> [BE] 로깅 적용 (#18)

- backend/src/main/java/com/backjoongwon/cvi/user/application/UserService.java
- backend/src/main/java/com/backjoongwon/cvi/user/domain/AgeRange.java
- backend/src/main/java/com/backjoongwon/cvi/user/domain/User.java
- backend/src/main/java/com/backjoongwon/cvi/user/dto/UserRequest.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/logback-spring.xml
- backend/src/test/java/com/backjoongwon/cvi/user/application/UserServiceTest.java
> [BE] 버그 수정 및 연령대 한글 반환값 수정 (#69)

- frontend/src/components/VaccinationState/VaccinationState.js
- frontend/src/components/VaccinationState/VaccinationState.styles.js
- frontend/src/components/common/BaseLayout/BaseLayout.styles.js
- frontend/src/components/common/DonutChart/DonutChart.js
- frontend/src/components/common/DonutChart/DonutChart.stories.js
- frontend/src/components/common/DonutChart/DonutChart.styles.js
- frontend/src/components/common/index.js
- frontend/src/pages/HomePage/HomePage.styles.js
> [FE] Donut Chart 컴포넌트 구현(#78)

- frontend/src/assets/icons/index.js
- frontend/src/assets/icons/menu.svg
- frontend/src/components/Preview/Preview.styles.js
- frontend/src/components/PreviewList/PreviewList.styles.js
- frontend/src/components/VaccinationState/VaccinationState.styles.js
- frontend/src/components/common/BaseLayout/BaseLayout.js
- frontend/src/components/common/BaseLayout/BaseLayout.styles.js
- frontend/src/components/common/Button/Button.styles.js
- frontend/src/components/common/Frame/Frame.styles.js
- frontend/src/components/common/Selection/Selection.styles.js
- frontend/src/components/common/SidebarMobile/SideBarMobile.js
- frontend/src/components/common/SidebarMobile/SideBarMobile.stories.js
- frontend/src/components/common/SidebarMobile/SideBarMobile.styles.js
- frontend/src/components/common/Tabs/Tabs.styles.js
- frontend/src/components/common/index.js
- frontend/src/pages/HomePage/HomePage.styles.js
- frontend/src/pages/ReviewDetailPage/ReviewDetailPage.styles.js
- frontend/src/pages/ReviewPage/ReviewPage.styles.js
> [FE] 전체적인 모바일 레이아웃 구현(#81)

- frontend/src/components/CommentForm/CommentForm.js
- frontend/src/components/CommentItem/CommentItem.js
- frontend/src/components/CommentItem/CommentItem.styles.js
- frontend/src/components/ReviewWritingModal/ReviewWritingModal.js
- frontend/src/components/common/Avatar/Avatar.js
- frontend/src/components/common/Label/Label.js
- frontend/src/components/common/SideBar/SideBar.styles.js
- frontend/src/constants/index.js
- frontend/src/constants/limit.js
- frontend/src/constants/message.js
- frontend/src/pages/ReviewDetailPage/ReviewDetailPage.js
- frontend/src/requests.js
- frontend/src/service/index.js
> [FE] 상세 페이지 댓글 생성, 삭제 기능 구현 (#66)

- frontend/src/components/CommentForm/CommentForm.js
- frontend/src/components/CommentItem/CommentItem.js
- frontend/src/components/CommentItem/CommentItem.styles.js
- frontend/src/constants/message.js
- frontend/src/requests.js
- frontend/src/service/index.js
> [FE] 상세 페이지 댓글 수정 기능 구현 (#66)

- frontend/src/components/common/SideBarMobile/SideBarMobile.styles.js
> [FE] 로그인/로그아웃 버튼 위치 조정 (#98)

- backend/src/main/java/com/backjoongwon/cvi/DataLoader.java
- backend/src/main/java/com/backjoongwon/cvi/user/domain/User.java
- backend/src/main/java/com/backjoongwon/cvi/user/dto/UserRequest.java
- backend/src/test/java/com/backjoongwon/cvi/user/application/UserServiceTest.java
- backend/src/test/java/com/backjoongwon/cvi/user/domain/UserTest.java
- backend/src/test/java/com/backjoongwon/cvi/user/ui/UserControllerTest.java
> [BE] 사진 인증 (유저 정보 업데이트) (#117)

- backend/src/main/java/com/backjoongwon/cvi/auth/domain/authorization/NaverAuthorization.java
- backend/src/main/java/com/backjoongwon/cvi/comment/domain/Comment.java
- backend/src/main/java/com/backjoongwon/cvi/common/domain/entity/BaseEntity.java
- backend/src/main/java/com/backjoongwon/cvi/like/domain/Like.java
- backend/src/main/java/com/backjoongwon/cvi/post/domain/Post.java
- backend/src/main/java/com/backjoongwon/cvi/user/domain/User.java
> [BE] Auditing LastModifiedAt 추가 (#101)

- frontend/.env
- frontend/.gitignore
> [FE] .env 파일 숨김 처리 (#143)

- frontend/src/components/PreviewList/PreviewList.js
- frontend/src/pages/ReviewPage/ReviewPage.js
- frontend/src/requests.js
- frontend/src/service/index.js
> [FE] ReviewPage 페이징 API 수정사항 반영 (#152)

- frontend/src/components/VaccinationState/VaccinationState.js
- frontend/src/components/VaccinationState/VaccinationState.styles.js
> [FE] DonutChart API 적용 (#175)

- backend/build.gradle
- backend/src/main/java/com/backjoongwon/cvi/comment/domain/Comment.java
- backend/src/main/java/com/backjoongwon/cvi/like/domain/Like.java
- backend/src/main/java/com/backjoongwon/cvi/post/domain/Post.java
- backend/src/main/java/com/backjoongwon/cvi/publicdata/domain/PublicData.java
- backend/src/main/java/com/backjoongwon/cvi/publicdata/domain/VaccinationStatistic.java
- backend/src/main/resources/db/migration/V20210809__Create_init.sql
- backend/src/main/resources/logback-spring.xml
> [BE] DB 마이그레이션(flyway) 적용 (#65)

- frontend/src/components/RegionalStateTable/RegionalStateTable.js
- frontend/src/components/RegionalStateTable/RegionalStateTable.styles.js
- frontend/src/components/common/MapChart/MapChart.js
- frontend/src/components/common/MapChart/MapChart.styles.js
> [FE] 페이지 전체적인 레이아웃 수정 (#206)

- frontend/src/App.js
- frontend/src/components/Comment/Comment.js
- frontend/src/components/CommentForm/CommentForm.js
- frontend/src/components/CommentItem/CommentItem.js
- frontend/src/components/RegionalStateChart/RegionalStateChart.js
- frontend/src/components/RegionalStateChart/RegionalStateChart.styles.js
- frontend/src/components/VaccinationSchedule/VaccinationSchedule.styles.js
- frontend/src/components/VaccinationState/VaccinationState.js
- frontend/src/components/common/MapChart/MapChart.js
- frontend/src/components/common/Route/Route.js
- frontend/src/components/common/SideBar/SideBar.js
- frontend/src/components/common/SideBarMobile/SideBarMobile.js
- frontend/src/components/common/SideBarMobile/SideBarMobile.styles.js
- frontend/src/components/common/ToggleButton/ToggleButton.styles.js
- frontend/src/components/common/index.js
- frontend/src/constants/message.js
- frontend/src/pages/HomePage/HomePage.js
- frontend/src/pages/MyPage/MyPage.js
- frontend/src/pages/ReviewDetailPage/ReviewDetailPage.js
- frontend/src/pages/ReviewPage/ReviewPage.js
- frontend/src/pages/StatePage/StatePage.js
- 댓글 페이징 적용 후 CRUD 에러 수정 
- 로그아웃 시, HomePage로 이동 기능 구현
- 로그인 유무에 따라서 접근 가능한 페이지 구분
- BarChart, MapChart 로딩 적용
#208
> [FE] 댓글 페이징 에러 수정 (#208)

- frontend/src/constants/message.js
- frontend/src/pages/MyPageCommentReview/MyPageCommentReview.js
- frontend/src/pages/MyPageShotVerification/MyPageShotVerification.js
- frontend/src/pages/MyPageShotVerification/MyPageShotVerification.styles.js
> [FE] 접종 인증 페이지 인증 로직 추가 (#213)

- frontend/src/components/Comment/Comment.js
- frontend/src/components/CommentForm/CommentForm.js
- frontend/src/components/Preview/Preview.js
- frontend/src/components/PreviewItem/PreviewItem.js
- frontend/src/components/PreviewList/PreviewList.js
- frontend/src/constants/message.js
- frontend/src/pages/MyPageAccount/MyPageAccount.js
- frontend/src/pages/MyPageShotVerification/MyPageShotVerification.js
- frontend/src/pages/ReviewPage/ReviewPage.js
- frontend/src/pages/SignupPage/SignupPage.js
> [FE] 데모 전 최종 리팩토링 (#224)

- frontend/env/.env.production
- frontend/package.json
> [FE] .env.production login callback url 수정 (#228)

- backend/src/main/java/com/backjoongwon/cvi/auth/domain/authorization/KakaoAuthorization.java
- frontend/env/.env.production
> chore: domain url 수정

- backend/src/main/java/com/backjoongwon/cvi/image/domain/Image.java
- backend/src/main/java/com/backjoongwon/cvi/post/domain/Images.java
- backend/src/main/java/com/backjoongwon/cvi/post/dto/PostResponse.java
- backend/src/main/java/com/backjoongwon/cvi/post/dto/PostWithCommentResponse.java
- backend/src/test/java/com/backjoongwon/cvi/post/service/PostMyPageServiceTest.java
- backend/src/test/java/com/backjoongwon/cvi/user/controller/UserControllerTest.java
> [BE] 게시글 이미지 순서 보장, 마이페이지 게시글 응답에 이미지 포함 (#254)

- frontend/.prettierrc
- frontend/env/.env.development
- frontend/env/.env.local
- frontend/package.json
- frontend/src/components/VaccinationSchedule/VaccinationSchedule.js
- frontend/webpack.config.js
- frontend/yarn.lock
- prettier
- package.json
- webpack
- env
> [FE] 환경 변수 및 세팅 수정

- frontend/src/components/common/HorizontalBarChart/HorizontalBarChart.js
> [FE] HorizontalBarChart 애니메이션이 적용되지 않는 문제 수정 (#270)

- frontend/src/components/MyCommentsItem/MyCommentsItem.js
- frontend/src/components/MyCommentsItem/MyCommentsItem.styles.js
- frontend/src/pages/MyPageCommentReview/MyPageCommentReview.styles.js
> [FE] 마이페이지 댓글 단 글에 첨부된 이미지 표시 (#268)

- .gitmodules
- backend/deploy/start.sh
- backend/src/main/java/com/backjoongwon/cvi/auth/domain/authorization/KakaoAuthorization.java
- backend/src/main/java/com/backjoongwon/cvi/common/EnvSecret.java
- backend/src/main/resources/application.yml
- backend/src/test/resources/application.yml
#253 
YAML 설정을 통해 카카오 소셜로그인 redirectUrl이 local, dev, prod 환경별로 다르게 적용되도록 수정했습니다.
로컬 환경, 배포 환경에서 테스트 했습니다.
반드시 [서브모듈 PR](https://github.com/taehee-kim-dev/cvi-backend-secret/pull/1)을 먼저 approve한 후, 이 PR을 approve 해 주세요.
지금 이 PR처럼 프로덕션 코드와 서브모듈의 코드가 같이 수정되는 경우,
[서브모듈 PR](https://github.com/taehee-kim-dev/cvi-backend-secret/pull/1)처럼 우리팀이 기존에 하던방식과 동일하게 branch를 따서 작업한 후 [서브모듈 Repository](https://github.com/taehee-kim-dev/cvi-backend-secret)에 PR을 올려주세요.
그리고 해당 PR 링크를 이 PR처럼 내용에 남겨주세요.
서브모듈을 PR로 관리하지 않을 경우, 
1. 인비가 서브모듈 수정 후 main브랜치에 바로 push했다.
2. 검프가 배포를 했다.
3. 젠킨스에서는 항상 서브모듈의 코드를 가져올 때, main브랜치의 코드를 가져온다.
4. 검프가 배포한 프로덕션 코드와 인비가 push한 서브모듈의 코드 설정이 맞지 않는다.
5. 장애가 발생한다.
위와 같은 상황이 발생합니다.
그래서 제가 제안하고 싶은 방식은 아래와 같아요.
서브모듈 코드가 수정되어야 할 경우,
1. CVI 메인 Repository는 기존 방식과 동일하게 `feature/backend-issue{CVI …
> [BE] 카카오 RedirectUrl dev, prod 설정 (#253)

- backend/src/main/java/com/backjoongwon/cvi/publicdata/domain/VaccinationStatistics.java
- backend/src/main/java/com/backjoongwon/cvi/publicdata/dto/KoreaVaccinationDataFactory.java
- backend/src/main/java/com/backjoongwon/cvi/publicdata/service/PublicDataService.java
- backend/src/test/java/com/backjoongwon/cvi/publicdata/domain/VaccinationStatisticFactory.java
- backend/src/test/java/com/backjoongwon/cvi/publicdata/domain/VaccinationStatisticsTest.java
#274 의 이슈를 해결했어요.
변경사항은 아래와 같습니다! 
- RegionVaccinationDataFactory -> KoreaVaccinationDataFactory 
- findRecentlyStatistics -> findKoreaRecentlyStatistics
> [BE] 백신 접종률 리펙터링 및 테스트 코드 작성 (#274)

- .github/workflows/front-dev-deploy.yml
> [FE] 깃허브 액션 커맨드 수정

- frontend/src/pages/ReviewDetailPage/ReviewDetailPage.styles.js
> [FE] 리뷰 개행 처리 (#265)

- frontend/public/index.html
#288
---
이미지는 일단 임시로 이걸로 했습니당
- open graph image path가 상대 경로는 안된다고 해서, github upload url로 설정했는데 이 부분 같이 이야기 하면 좋을 것 같아요!
- 제목이나 설명 관련해서 의견 주세욥
> [FE] 오픈 그래프 추가(#288)

- backend/app-cvi-api/src/main/java/com/cvi/controller/PostController.java
- backend/app-cvi-api/src/main/java/com/cvi/service/post/PostService.java
- backend/app-cvi-api/src/test/java/com/cvi/controller/PostControllerTest.java
- backend/app-cvi-api/src/test/java/com/cvi/service/PostFindServiceTest.java
- backend/domain-cvi/src/main/java/com/cvi/post/domain/repository/PostQueryDsl.java
- backend/domain-cvi/src/main/java/com/cvi/post/domain/repository/PostRepositoryImpl.java
> [BE] 페이징 시, 특정 시간 이내에 생성된 게시물만 조회하는 기능 제거 (#299)

- frontend/src/components/@common/BaseLayout/BaseLayout.js
- frontend/src/components/preview/Preview/Preview.js
- frontend/src/components/preview/PreviewList/PreviewList.js
- frontend/src/components/statistics/VaccinationState/VaccinationState.js
- frontend/src/hooks/index.js
- frontend/src/hooks/useLike.js
- frontend/src/hooks/useMovePage.js
- frontend/src/pages/HomePage/HomePage.js
- frontend/src/pages/MyPageCommentReview/MyPageCommentReview.js
- frontend/src/pages/MyPageLikeReview/MyPageLikeReview.js
- frontend/src/pages/MyPageReview/MyPageReview.js
- frontend/src/pages/OAuthPage/OAuthPage.js
- frontend/src/pages/ReviewDetailPage/ReviewDetailPage.js
- frontend/src/pages/ReviewEditPage/ReviewEditPage.js
- frontend/src/pages/ReviewPage/ReviewPage.js
- frontend/src/pages/SignupPage/SignupPage.js
> [FE] useMovePage 커스텀훅 생성 및 적용(#311)

- backend/app-cvi-api/docs/asciidoc/index.adoc
> [BE] Spring REST Docs 빠진 부분 채우기 (댓글) (#304)
